apiVersion: v1
kind: Service
metadata:
  name: transaction-api
  namespace: ledgerflow
spec:
  selector:
    app: transaction-api
  type: NodePort
  ports:
    - port: 2002
      targetPort: 8080
      nodePort: 30002