apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgersummaries-api
  namespace: ledgerflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledgersummaries-api
  template:
    metadata:
      labels:
        app: ledgersummaries-api
    spec:
      containers:
        - name: ledgersummaries-api
          image: lucasfogliarini/ledgersummaries-api:latest
          ports:
            - containerPort: 8080
          resources:
          requests:
            cpu: "0.5"
            memory: "0.5Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          envFrom:
            - secretRef:
                name: ledgerflow-secrets
          livenessProbe: # LivenessProbe verifica se o Pod está vivo e reinicia se necessário
            httpGet:
              path: /health/live
              port: 8080
            failureThreshold: 1 # Reinicia o Pod imediatamente ao detectar falha
          readinessProbe: # ReadinessProbe verifica se o Pod está pronto para receber tráfego.
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 20 # Intervalo entre as verificações
            timeoutSeconds: 5 # Tempo de espera para a resposta do probe
            failureThreshold: 1 # Pod continua rodando, mas é removido dos endpoints do Service
            successThreshold: 1 # Número de sucessos necessários para considerar o Pod pronto para tráfego novamente
            initialDelaySeconds: 2 # Tempo de espera antes de iniciar as verificações
