apiVersion: v1
kind: Service
metadata:
  name: ledgersummaries-api
  namespace: ledgerflow
spec:
  selector:
    app: ledgersummaries-api
  type: NodePort
  ports:
    - port: 2003
      targetPort: 8080
      nodePort: 30003