apiVersion: v1
kind: Service
metadata:
  name: transaction-api
  namespace: ledgerflow
  labels:
    app.kubernetes.io/name: transaction-api
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: transaction-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080