apiVersion: v1
kind: Secret
metadata:
  name: ledgerflow-secrets
  namespace: ledgerflow
type: Opaque
stringData:
  JwtSettings__Authority: "http://keycloak.svc.cluster.local:2000/realms/ledgerflow"
  JwtSettings__Audience: "ledgerflow-api"
  ConnectionStrings__LedgerFlow: "Server=sqlserver.svc.cluster.local,2001;Database=LedgerFlow;User Id=sa;Password=Ledgerflow!123;Encrypt=True;TrustServerCertificate=True;Timeout=30;"
  ConnectionStrings__Redis: "redis.svc.cluster.local:2004,connectTimeout=2000"
